name: C++ BUild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build the main.cpp
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: sudo apt install -y libcppunit-dev
    - name : config
      run: ./configure
    - name: Make
      run: make
